# Generated by Django 6.1 on 2026-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier.', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Interest',
                'verbose_name_plural': 'Career Interests',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='professional_interests',
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='hero_heading',
            field=models.CharField(default='Turning ideas into impact.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='professional_direction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='professional_focus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
