# Generated by Django 6.1 on 2026-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutinterest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_code', models.CharField(blank=True, help_text='Example: AI, DA, SD', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Interest',
                'verbose_name_plural': 'Career Interests',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CareerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Career Objective', max_length=150)),
                ('objective', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Objective',
                'verbose_name_plural': 'Career Objective',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='AboutInterest',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='career_objective',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='professional_direction',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='professional_focus',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='introduction_heading',
            field=models.CharField(default='My Introduction', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='tagline',
            field=models.CharField(default='Turning Complexity into Clarity.', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='title',
            field=models.CharField(default='About Me', max_length=200),
        ),
    ]
