# Generated by Django 6.1 on 2026-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional Projects'), ('academic', 'Academic Projects'), ('personal', 'Personal Projects')], default='personal', max_length=20),
        ),
    ]
