# Generated by Django 6.1 on 2026-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('degree_type', models.CharField(choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('other', 'Other')], default='other', max_length=20)),
                ('institute', models.CharField(max_length=200)),
                ('board', models.CharField(blank=True, help_text='Enter the board for school/college education.', max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Select this if you are currently studying here.')),
                ('grade', models.CharField(blank=True, help_text='For Matric/Intermediate, e.g. A+ or A.', max_length=20)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='For university education, e.g. 3.60.', max_digits=4, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-start_year'],
            },
        ),
    ]
