# Generated by Django 6.1 on 2026-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_count', models.PositiveIntegerField(default=0)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('technologies_count', models.PositiveIntegerField(default=0)),
                ('achievements_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Stats',
                'verbose_name_plural': 'Home Stats',
            },
        ),
    ]
