# Generated by Django 6.1 on 2026-09-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default="Let's Connect", max_length=100)),
                ('title', models.CharField(default="Let's Work Together", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Contact Me', max_length=100)),
                ('button_url', models.CharField(default='/contact/', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home CTA',
                'verbose_name_plural': 'Home CTA',
            },
        ),
        migrations.CreateModel(
            name='HomeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Process Step',
                'verbose_name_plural': 'Home Process Steps',
                'ordering': ['display_order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('services', 'Services'), ('projects', 'Featured Projects'), ('process', 'My Process')], max_length=30, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_code', models.CharField(help_text='Example: AI, DA, SE, WD', max_length=5)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Service',
                'verbose_name_plural': 'Home Services',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='cv_button_text',
            field=models.CharField(default='Download CV', max_length=100),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='work_button_text',
            field=models.CharField(default='View My Work', max_length=100),
        ),
        migrations.AddField(
            model_name='homeprofile',
            name='work_button_url',
            field=models.CharField(default='/projects/', max_length=300),
        ),
    ]
