# Generated by Django 6.1 on 2026-09-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecta_homeprocess_homesection_homeservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homestats',
            options={'verbose_name': 'Home Statistics', 'verbose_name_plural': 'Home Statistics'},
        ),
        migrations.AlterField(
            model_name='homecta',
            name='button_text',
            field=models.CharField(default='Get In Touch', max_length=100),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='label',
            field=models.CharField(default="Let's Talk", max_length=100),
        ),
        migrations.AlterField(
            model_name='homeprofile',
            name='cv_button_text',
            field=models.CharField(default='Download My CV', max_length=100),
        ),
        migrations.AlterField(
            model_name='homeprofile',
            name='greeting',
            field=models.CharField(default="Hello, I'm", max_length=100),
        ),
    ]
